// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/signup": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/workflow/:id": {
    params: {
      "id": string;
    };
  };
  "/templates": {
    params: {};
  };
  "/api/generate/text-to-image": {
    params: {};
  };
  "/api/generate/image-to-video": {
    params: {};
  };
  "/api/generate/text-to-video": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/signup" | "/dashboard" | "/workflow/:id" | "/templates" | "/api/generate/text-to-image" | "/api/generate/image-to-video" | "/api/generate/text-to-video";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/signup.tsx": {
    id: "routes/signup";
    page: "/signup";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/dashboard";
  };
  "routes/workflow.$id.tsx": {
    id: "routes/workflow.$id";
    page: "/workflow/:id";
  };
  "routes/templates.tsx": {
    id: "routes/templates";
    page: "/templates";
  };
  "routes/api.generate.text-to-image.tsx": {
    id: "routes/api.generate.text-to-image";
    page: "/api/generate/text-to-image";
  };
  "routes/api.generate.image-to-video.tsx": {
    id: "routes/api.generate.image-to-video";
    page: "/api/generate/image-to-video";
  };
  "routes/api.generate.text-to-video.tsx": {
    id: "routes/api.generate.text-to-video";
    page: "/api/generate/text-to-video";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/signup": typeof import("./app/routes/signup.tsx");
  "routes/dashboard": typeof import("./app/routes/dashboard.tsx");
  "routes/workflow.$id": typeof import("./app/routes/workflow.$id.tsx");
  "routes/templates": typeof import("./app/routes/templates.tsx");
  "routes/api.generate.text-to-image": typeof import("./app/routes/api.generate.text-to-image.tsx");
  "routes/api.generate.image-to-video": typeof import("./app/routes/api.generate.image-to-video.tsx");
  "routes/api.generate.text-to-video": typeof import("./app/routes/api.generate.text-to-video.tsx");
};